### ISSUE TITLE
I am getting this error when using geo_to_h3

### ISSUE THREAD

**Issue by Tanay0510** [uber/h3-py#100]
"module 'h3' has no attribute 'geo_to_h3'", 'occurred at index 313626

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully fix these install issues. Could you please try installing with `pip install h3==3.6.1` and let us know how it works?

I'll close this for now. Please re-open if the issue persists!

**Comment by anitagraser** [comment]
Is this issue back in 4.1.1?

**Comment by dfellis** [comment]
The `4.1.0` and `4.1.1` releases of `h3-py` switched to the [C H3 4.0 naming scheme](https://h3geo.org/docs/api/indexing#latlngtocell), so `geo_to_cell` has become `latlng_to_cell`.

**Comment by anitagraser** [comment]
Thank you for the prompt response, @dfellis

**Comment by ajfriend** [comment]
@peterdudfield, if you're still running into an error, please open a new issue and we can try to resolve there.
