### ISSUE TITLE
Can't install on ubuntu 16.04

### ISSUE THREAD

**Issue by nhoover** [uber/h3-py#106]
I have a simple Ubuntu 16.04 system running in VirtualBox. I want to install h3-py and have had no trouble installing other modules.

I have the required programs installed:

osboxes@osboxes:~$ cc --version
cc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

osboxes@osboxes:~$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

osboxes@osboxes:~$ cmake --version
cmake version 3.17.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

osboxes@osboxes:~$ git --version
git version 2.7.4

osboxes@osboxes:~$ pip --version
pip 20.1 from /home/osboxes/.local/lib/python2.7/site-packages/pip (python 2.7)

osboxes@osboxes:~$ pip freeze | grep -- 'Cython|scikit'
Cython==0.29.17
scikit-build==0.11.1

When I run: pip install git+https://github.com/uber/h3-py.git

After it runs happily for a while it dies with:

    [ 95%] Built target testH3ToLocalIj
    Scanning dependencies of target testH3Line
    [ 95%] Building C object src/h3lib/CMakeFiles/testH3Line.dir/src/apps/testapps/testH3Line.c.o
    [ 95%] Building C object src/h3lib/CMakeFiles/testH3Line.dir/src/apps/applib/lib/test.c.o
    [ 95%] Building C object src/h3lib/CMakeFiles/testH3Line.dir/src/apps/applib/lib/kml.c.o
    [ 97%] Building C object src/h3lib/CMakeFiles/testH3Line.dir/src/apps/applib/lib/utility.c.o
    [ 97%] Building C object src/h3lib/CMakeFiles/testH3Line.dir/src/apps/applib/lib/args.c.o
    [ 97%] Linking C executable bin/testH3Line
    [ 97%] Built target testH3Line
    [ 97%] Generating C source src/h3/_cy/edges.c
    Scanning dependencies of target edges
    [ 97%] Building C object src/h3/_cy/CMakeFiles/edges.dir/edges.c.o
    [ 97%] Linking C shared module edges.so
    /usr/bin/ld: ../../h3lib/lib/libh3.a(algos.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
    ../../h3lib/lib/libh3.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    src/h3/_cy/CMakeFiles/edges.dir/build.make:110: recipe for target 'src/h3/_cy/edges.so' failed
    make[2]: *** [src/h3/_cy/edges.so] Error 1
    CMakeFiles/Makefile2:6832: recipe for target 'src/h3/_cy/CMakeFiles/edges.dir/all' failed
    make[1]: *** [src/h3/_cy/CMakeFiles/edges.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "/home/osboxes/.local/lib/python2.7/site-packages/skbuild/setuptools_wrap.py", line 589, in setup
        cmkr.make(make_args, env=env)
      File "/home/osboxes/.local/lib/python2.7/site-packages/skbuild/cmaker.py", line 507, in make
        os.path.abspath(CMAKE_BUILD_DIR())))
    
    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release --
      Source directory:
        /tmp/pip-req-build-lEmE8M
      Working directory:
        /tmp/pip-req-build-lEmE8M/_skbuild/linux-x86_64-2.7/cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lEmE8M/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lEmE8M/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-XO0GIC/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/osboxes/.local/include/python2.7/h3 Check the logs for full command output.

Any ideas? The cmake working directory mentioned /tmp/pip-req-build-lEmE8M/_skbuild/linux-x86_64-2.7/cmake-build doesn't exist after this finishes.

**Comment by ajfriend** [comment]
I'm currently in the middle of trying to figure out how to build linux wheels, which should simplify installation in the long term: https://github.com/uber/h3-py/issues/107

I'm not sure this would work, but as a short term hack, could you try pulling the repo, and then installing with

```
CFLAGS='-fPIC' python setup.py install
```

@isaacbrodsky @dfellis @nrabinowitz Would any of you have other insight?

**Comment by nhoover** [comment]
Ok instead of building via pip install git+https://github.com/uber/h3-py.git

I created a directory and ran git clone git@github.com:uber/h3-py.git
Cloning into 'h3-py'...
remote: Enumerating objects: 377, done.
remote: Total 377 (delta 0), reused 0 (delta 0), pack-reused 377
Receiving objects: 100% (377/377), 12.45 MiB | 12.12 MiB/s, done.
Resolving deltas: 100% (159/159), done.
Checking connectivity... done.

Then:

osboxes@osboxes:~/h3$ cd h3-py/
osboxes@osboxes:~/h3/h3-py$ ls
appveyor.yml  CHANGELOG.md  CMakeLists.txt  dev_notes.md  LICENSE  makefile  readme.md  requirements-dev.txt  setup.py  src  tests  tox.ini
osboxes@osboxes:~/h3/h3-py$ CFLAGS='-fPIC' python setup.py install
--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/osboxes/h3/h3-py/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - failure
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Trying "Unix Makefiles" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/osboxes/h3/h3-py/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Unix Makefiles" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /home/osboxes/h3/h3-py/_skbuild/linux-x86_64-2.7/cmake-build
  Command:
    cmake /home/osboxes/h3/h3-py -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/home/osboxes/h3/h3-py/_skbuild/linux-x86_64-2.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python -DPYTHON_VERSION_STRING:STRING=2.7.12 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/osboxes/.local/lib/python2.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory

    /home/osboxes/h3/h3-py/src/h3lib

  does not contain a CMakeLists.txt file.


-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found Cython: /home/osboxes/.local/bin/cython  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
_modinit_prefix:init
_modinit_prefix:init
_modinit_prefix:init
_modinit_prefix:init
_modinit_prefix:init
-- Configuring incomplete, errors occurred!
See also "/home/osboxes/h3/h3-py/_skbuild/linux-x86_64-2.7/cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python2.7/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
    languages=cmake_languages
  File "/home/osboxes/.local/lib/python2.7/site-packages/skbuild/cmaker.py", line 240, in configure
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while configuring with CMake.
  Command:
    cmake /home/osboxes/h3/h3-py -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/home/osboxes/h3/h3-py/_skbuild/linux-x86_64-2.7/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python -DPYTHON_VERSION_STRING:STRING=2.7.12 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/osboxes/.local/lib/python2.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  Source directory:
    /home/osboxes/h3/h3-py
  Working directory:
    /home/osboxes/h3/h3-py/_skbuild/linux-x86_64-2.7/cmake-build
Please see CMake's output for more information.


Sure enough as it says there is nothing in src/h3lib
osboxes@osboxes:~/h3/h3-py$ ls src
h3  h3lib
osboxes@osboxes:~/h3/h3-py$ ls src/h3
api  CMakeLists.txt  _cy  __init__.py  _version.py
osboxes@osboxes:~/h3/h3-py$ ls src/h3lib/
osboxes@osboxes:~/h3/h3-py$

**Comment by ajfriend** [comment]
Ah, that's my mistake. After you clone, in the repo directory, run

```
git submodule update --init
pip install -r requirements-dev.txt
CFLAGS='-fPIC' python setup.py install
```

The `git submodule update --init` is the thing that pulls in the H3 C source code and places it in the `h3lib` directory.

**Comment by nhoover** [comment]
Great - that fixed the problem. But the install didn't work due to permissions. So I re-ran it with sudo and voila:

Installed /usr/local/lib/python2.7/dist-packages/h3-3.6.1-py2.7-linux-x86_64.egg
Processing dependencies for h3==3.6.1
Finished processing dependencies for h3==3.6.1
osboxes@osboxes:~/h3/h3-py$ python
Python 2.7.12 (default, Apr 15 2020, 17:07:12) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from h3 import h3
>>> h3.h3_get_base_cell('8928308280fffff')
20
>>> 

Thanks very much for your Sunday night help!

**Comment by ajfriend** [comment]
No problem! Let us know if you run into any other issues!
