### ISSUE TITLE
Create API examples with jupyter nbviewer 

### ISSUE THREAD

**Issue by TengHu** [uber/h3-py#12]

**Comment by camelia-c** [comment]
Moments ago, I made a pull request with examples of H3 and deck.gl in Urban Analytics. 

On nbviewer  it is available at:

[https://nbviewer.jupyter.org/github/camelia-c/h3-py/blob/master/docs/H3%20API%20examples%20on%20Urban%20Analytics.ipynb](https://nbviewer.jupyter.org/github/camelia-c/h3-py/blob/master/docs/H3%20API%20examples%20on%20Urban%20Analytics.ipynb)

Camelia

**Comment by TengHu** [comment]
@camelia-c 
Approved. Thank you for your contribution !

**Comment by nlicalzi** [comment]
@camelia-c looks awesome, thanks for taking care of this!

**Comment by psychemedia** [comment]
Trying to launch the repo with MyBinder throws an error because of the `None` item, which is not a valid Python package name,  in `requirements.txt`. Deleting the `requirement.txt` file, or setting it to an empty file by deleting the `None` item should rectify this.

**Comment by camelia-c** [comment]
The requirements needed are listed in the end of the notebook, in the Appendix. 
I've used a separate requirements_demo.txt for it.

**Comment by camelia-c** [comment]
I included a setup section inside the notebook, so now it's self-contained.
Best Regards,
Camelia

**Comment by psychemedia** [comment]
I also made a PR that includes all requirements files to autobuild a MyBinder container that runs the original notebook. (Note also the demo notebook contained a package name error and didn't run in Py3, both of which I fixed in the PR.)
