### ISSUE TITLE
Parent/child function corner-case behavior

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#136]
Some questions I have about what behavior we should have for some parent/child corner-cases.

Let `h = '8928308280fffff'`.

Questions:

```python
## return `None` or raise Exception?
h3.h3_to_parent(h, 10)

## return `h`, `None`, or raise Exception?
h3.h3_to_parent(h, 9)
```

```python
## return `None`, empty set, `{h}`, or raise Exception?
h3.h3_to_children(h, 9)

## return `None`, empty set, or raise Exception?
h3.h3_to_children(h, 8)
```

```python
## return `None` or raise Exception?
h3.h3_to_center_child(h, 8)

## return `h`, `None`, or raise Exception
h3.h3_to_center_child(h, 9)
```

**Comment by dfellis** [comment]
These are my opinions, but I'll support each one as I go.

> Some questions I have about what behavior we should have for some parent/child corner-cases.
> 
> Let `h = '8928308280fffff'`.
> 
> Questions:
> 
> ```python
> ## return `None` or raise Exception?
> h3.h3_to_parent(h, 10)

raise exception. This is a confusion of how the indexes work and an exception will probably help people exploring the API through a REPL, while actual behavior in live code shouldn't ever run into this (it would be a legitimate error)

> ## return `h`, `None`, or raise Exception?
> h3.h3_to_parent(h, 9)
> ```

This is definitely an opinion, but I think it should return `h`. Clearly a node can't be a parent of itself, but I could see someone using `h3_to_parent` to say "convert this mixed set of hexagons to a single resolution set and let Python's `set` handle deduplication".

> ```python
> ## return `None`, empty set, `{h}`, or raise Exception?
> h3.h3_to_children(h, 9)

Same as the prior, returning `h` seems most useful even if that's not technically correct, because it's a way to unify a set of mixed hexagons in the opposite direction.

> ## return `None`, empty set, or raise Exception?
> h3.h3_to_children(h, 8)
> ```

This should also be an Exception.

> ```python
> ## return `None` or raise Exception?
> h3.h3_to_center_child(h, 8)

Exception for same reasons as above.

> ## return `h`, `None`, or raise Exception
> h3.h3_to_center_child(h, 9)
> ```

`h` for the same reasons as above.

This reasoning is assuming that the user is operating on some mixed set of hexagons and wants to unify things to the min or max resolution in the set.

**Comment by ajfriend** [comment]
I think I mostly agree with you. Here's the summary:

```python
## raise Exceptions
h3.h3_to_parent(h, 10)
h3.h3_to_center_child(h, 8)
h3.h3_to_children(h, 8)

## `h` or Exception
h3.h3_to_parent(h, 9)
h3.h3_to_center_child(h, 9)

## `{h}` or Exception
h3.h3_to_children(h, 9)
```

For the last three examples, I'm still undecided on what would be best, but your arguments on mixed sets totally make sense.

**Comment by isaacbrodsky** [comment]
I agree with @dfellis on these. For what it's worth, I think that's the way they function in Java, too

**Comment by ajfriend** [comment]
Cool, so we'll go with:

```python
## raise Exceptions
h3.h3_to_parent(h, 10)
h3.h3_to_center_child(h, 8)
h3.h3_to_children(h, 8)

## return `h`
h3.h3_to_parent(h, 9)
h3.h3_to_center_child(h, 9)

## return `{h}`
h3.h3_to_children(h, 9)
```

**Comment by nrabinowitz** [comment]
Adding my support for @dfellis's reasoning. Presumably we should apply the same approach to the main lib when we have errors from this function - then you'd just be doing exactly what the main lib does.

**Comment by ajfriend** [comment]
Implemented here: https://github.com/uber/h3-py/pull/134
