### ISSUE TITLE
Vectorized h3.geo_to_h3()

### ISSUE THREAD

**Issue by DahnJ** [uber/h3-py#141]
If I want to get H3 hashes for an array, I can do something like

```python
import h3.api.numpy_int as h3
resolution = 10
coords = np.random.uniform(0, 60, (1000, 2))  # create random "coordinates"
result = np.array([h3.geo_to_h3(lat, lon, resolution) for lat, lon in coords])
```

It would be great if `h3.geo_to_h3` could be vectorized ~~as a Numpy ufunc~~, so that one could do something along the lines of

```python
result = h3.geo_to_h3_ufunc(coords, resolution)
```

possibly getting the results much faster since the loop would happen at the C level.

Is this currently possible, or planned in the near future? If not, what would one need to do to implement it? Thank you!

**edit**: More accurate post title & strikethrough Numpy ufunc

**Comment by ajfriend** [comment]
I think that's a great use case!

However, I'm not sure how to make numpy ufuncs with Cython (which is what h3-py) is written in.
That might not be necessary, as ufuncs (in general) do some fancy array broadcasting stuff, and I'm not sure this function needs to handle arrays with arbitrary numbers of dimensions. I feel like 1D arrays are probably the desired use case (correct me if I'm wrong!).

Would it suffice to have a function that acts as it currently does on scalar inputs, but would also handle things like

```python
h3.geo_to_h3_ufunc(lat_array, lng_array, resolution_array)
```

I suppose we'd also want it to handle mixtures of scalar and 1D array inputs, and do the expected thing with

```python
h3.geo_to_h3_ufunc(lat_array, 0.0, 10)
```

Does that sound like a reasonable interface? Or would we actually want to make this a full-fledged ufunc? @isaacbrodsky @dfellis @nrabinowitz, if you all have any thoughts?

**Comment by DahnJ** [comment]
Thank you for the response. Yes, you're right, I'm still a bit hazy on these topics, but I think it makes sense that `geo_to_h3` is not an actual ufunc even from an API perspective, as it doesn't really "operate on ndarrays in an element-by-element fashion", but rather "operates on (n, 2) arrays in a row-by-row fashion". Plus there's the fact that ufuncs are not really written in Cython, as you mentioned.

I did not think of the possibility of using a `resolution_array`. I don't know about the API perspective, for I would imagine the speedup there wouldn't be as great and thus for me, it would be sufficient for `geo_to_h3` to accept only a single resolution at a time, looping from Python if necessary.

What I'm after is eliminating Python from the loop. For that, Cython should suffice.

**Comment by DahnJ** [comment]
I tried to hack a simple `geo_to_h3_vect()` in https://github.com/DahnJ/h3-py/commit/f98c04faa3039f125707d94bcbe29f99ce7c37c2

Performance:

```python
In [1]: import numpy as np
In [2]: import h3                 
In [3]: lats = np.random.uniform(0, 90, 1_000_000) 
In [4]: lons = np.random.uniform(0, 90, 1_000_000)                                                      

In [5]: %timeit [h3.geo_to_h3(lat, lon, 10) for lat, lon in zip(lats, lons)]                            
2.15 s ± 85.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit np.asarray(h3.geo_to_h3_vect(lats, lons, 10))                                           
 1.39 s ± 33.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)              
```

which is perhaps not as big an improvement as I hoped. 

At the same time, I would bet this can be improved by better Cython usage?

**Comment by ajfriend** [comment]
Awesome! Your code is how I would think of doing it, too. It is a bit disappointing we don't get a bigger speedup. I'm not a Cython optimization expert, but let's see if we can improve things a bit. (Perhaps @kwmsmith would be interested, too.)

What does the annotated Cython HTML output look like? I wonder if your code is hitting Python unexpectedly.

Another idea might be to unwrap the `deg2coord` function, and just inline the code. It isn't too complicated, and you can probably do the degrees to radians conversion in a vectorized way. You could re-use the same `h3lib.GeoCoord c` and just stuff the `c.lat` and `c.lng` values in each iteration. Not sure if that will help, but probably worth a try.

**Comment by ajfriend** [comment]
Also, your tests above are using the `str` representation. For speed, I would recommend using the `uint64` representation like in `h3.api.numpy_int`. I wonder how much that might speed things up.

**Comment by DahnJ** [comment]
Thank you for the suggestions, @ajfriend 

Here are the results. I would say they don't point to any/much further improvement.

### Using `h3.api.numpy_int`

```python
import numpy as np
import h3.api.numpy_int as h3
lats = np.random.uniform(0, 90, 1_000_000) 
lons = np.random.uniform(0, 90, 1_000_000)                   

%timeit -r 10 [h3.geo_to_h3(lat, lon, 10) for lat, lon in zip(lats, lons)]
# 1.82 s ± 34.1 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 np.asarray(h3.geo_to_h3_vect(lats, lons, 10))      
# 1.32 s ± 35 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
```          

### Inlining `coordToDeg`
I have attempted to inline the function `coordToDeg` into `geo_to_h3_vect` in https://github.com/DahnJ/h3-py/commit/bbd14c706ef0d2cb7e017a090631b89a6703f141#diff-67dbc6b3859920565c2b3016958781da

```python
# Same setup
%timeit -r 10 np.asarray(h3.geo_to_h3_vect(lats, lons, 10))                
# 1.3 s ± 22.2 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
```

There doesn't appear to be a (statistically significant) improvement from the first Cython version.

### Cython HTML output
Sadly I didn't manage to produce the report using skbuild. I tried [setting CYTHON_ANNOTATE on](https://github.com/DahnJ/h3-py/commit/bbd14c706ef0d2cb7e017a090631b89a6703f141#diff-af3b638bc2a3e6c650974192a53c7291) in CMakeLists.txt, but perhaps that's not the way to do it? I am not very familiar with cmake and even less familiar with skbuild, so I'm likely doing it wrong.

**Comment by ajfriend** [comment]
I played around with this a bit myself (along with another vectorized function), and got similar results: https://github.com/uber/h3-py/blob/vect/test.ipynb

It looks like the bottleneck is indeed the computation in `h3lib.geoToH3`, so I'm not sure there are any easy optimization wins beyond what we've got so far.

Let me know if this **rough** interface looks useful to you in the short term: https://github.com/uber/h3-py/pull/147

I'm not yet sure how exactly these functions would fit into the existing API, but I can throw them up in a PyPI release under something like the `h3.unstable.*` namespace to make them easy for you to use in the short term, as we try to figure out how they'll fit in to the long-term API.

**Comment by DahnJ** [comment]
Yes, that sounds great, I am glad this is slowly making its way into the library. The speedup is not amazing, but definitely not insignificant either.

If there is/will be something I could help with, I'd be happy to contribute as well.

**Comment by ajfriend** [comment]
@DahnJ Check out https://github.com/uber/h3-py/blob/vect/test.ipynb to see if that looks useful to you.

I also threw in a simple multithreading example, as that could get you some speedups on multicore systems.

**Comment by DahnJ** [comment]
@ajfriend yes, thank you, it absolutely does!

**Comment by ajfriend** [comment]
Closed by https://github.com/uber/h3-py/pull/147
