### ISSUE TITLE
Need python binding for experimentalLocalIjToH3

### ISSUE THREAD

**Issue by karunaahuja** [uber/h3-py#150]
Currently, we have a Flink pipeline which converts hex map values to axial co-ordinates. We need to be able to create a batch job to convert this data back to the hex map given the hex address of the origin. While the java API exists for it, a python binding does not. Could we have this binding available? 

Let me know if you need any other details.

**Comment by ajfriend** [comment]
Closed by https://github.com/uber/h3-py/pull/155
