### ISSUE TITLE
Example using `cimport h3` in external code for speed

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#152]

**Comment by kylebarron** [comment]
Just a note I'm guessing there would need to be more `.pxd` files in order for the end-user `cimport` to work. In Jupyter:

```
> ipython
Python 3.8.3 (default, May 19 2020, 13:54:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext Cython
   ...:

In [2]: %%cython
   ...: cimport h3
   ...:
   ...:

Error compiling Cython file:
------------------------------------------------------------
...
cimport h3
       ^
------------------------------------------------------------

/Users/kyle/.ipython/cython/_cython_magic_f4fb333f094afe9fe31d61aa9102128e.pyx:1:8: 'h3.pxd' not found
```

Does that work for you?

**Comment by kylebarron** [comment]
It seems like this should work by adding `.pxd` definition files. Anything `cimport`'ed needs to have a corresponding `.pxd`. One note is that any code that calls `cimport h3` looks like it'll need a path to `h3api.h` as well

```
> ipython
Python 3.8.3 (default, May 19 2020, 13:54:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext cython

In [2]: %%cython
   ...: from h3._cy cimport util
   ...:
   ...:
/Users/kyle/.ipython/cython/_cython_magic_2b223eeb87eac923ee742a354e855a5a.c:625:10: fatal error:
      'h3api.h' file not found
#include "h3api.h"
         ^~~~~~~~~
1 error generated.
```

This was run in the `h3-py` root folder, letting the import find the package by file path. I think that the `.pxd` files might not be distributed as package data, so it won't work with the pip-installed `h3-py`.

Maybe it would be possible to define files like `h3api.h` and `.pxd` as package data included in the build?

**Comment by ajfriend** [comment]
Makes sense. My impression was that this should be possible theoretically, but I don't know if I've ever seen any smaller projects implement it and it get used elsewhere. Probably just `numpy`, but that's a hard code base to cheat off of :)

Let me know if you get any further with this! I'll try to revisit it at some point, but if you beat me to it with a PR, that'd be great too!

**Comment by kylebarron** [comment]
> Probably just `numpy`, but that's a hard code base to cheat off of :)

One thing I noticed in my research is that apparently _Cython_ provides those definitions, not the numpy project itself. https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd

> Maybe it would be possible to define files like `h3api.h` and `.pxd` as package data included in the build?

When cython code uses numpy, it needs to include the numpy headers by using [`np.get_include()`](https://numpy.org/devdocs/reference/generated/numpy.get_include.html) in the build step. 

So maybe similarly `h3-py` could provide a `h3.unstable.get_include` to get the location of `h3api.h`. And downstream code that calls `cimport h3` would do a similar process as one does with `cimport numpy`.

**Comment by ajfriend** [comment]
Randomly thinking about this again. Here's some docs on `scipy` doing the same thing: https://docs.scipy.org/doc/scipy/dev/contributor/public_cython_api.html
