### ISSUE TITLE
Is the the H3 hexagon ID deterministic?

### ISSUE THREAD

**Issue by CooperData** [uber/h3-py#160]
I am working on a project where we save h3 IDs for given points over time, and then we use the ID to join them together.
After the last package release, I found the matchings were in slightly shifted geographies. In more detail, the same h3 id, refers now to something more to the west of the points previously calculated. 

Am I correct to think the output might change over time? It seems to be the case.

**Comment by dfellis** [comment]
That absolutely should not be the case.

The python library recently went through a significant refactoring to Cython bindings versus ctypes. It's possible a regression occurred here. Can we get more details about this? Some example H3 IDs that have shifted? I would like to compare it with [h3-js](https://github.com/uber/h3-js) and earlier versions of h3-py.

**Comment by CooperData** [comment]
@dfellis I found out the premise of my question is not correct. There was another error that was introduced on the same day that this last release was created and I thought they were related. I will close this issue. Sorry for the confusion.
