### ISSUE TITLE
module 'h3' has no attribute 'geo_to_h3'

### ISSUE THREAD

**Issue by MHong94** [uber/h3-py#165]
I've tried both PyPi and conda-forge on 3.6.4, and I'm getting this error.

**Comment by sxwebster** [comment]
Same thing on fresh install via pip 15 Feb 2025

The basic example below does not work:

```
import h3

h3_index = h3.geo_to_h3(37.3615593, -122.0553238, 8)
polygon = h3.h3_to_geo_boundary(h3_index, geo_json=False)
```
