### ISSUE TITLE
3.6.4: Build breaks: a parameter list without types is only allowed in a function definition static PyObject* __pyx_convert__to_py___pyx_ctuple_double__and_double(__pyx_ctuple_double__and_double);

### ISSUE THREAD

**Issue by yurivict** [uber/h3-py#170]
Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/549877/logs/errors/py37-h3-3.6.4.log

FreeBSD 12.1

clang-8

**Comment by isaacbrodsky** [comment]
I did a quick test on a FreeBSD VM and I wasn't able to get this far. I instead got an error about "No module named 'skbuild'". It would be helpful if you could add instructions on how you started the build.

**Comment by ajfriend** [comment]
Closing this for now. Feel free to re-open if this is still an issue.
