### ISSUE TITLE
is it possible building wheels for alpine linux as well?

### ISSUE THREAD

**Issue by MuslimBeibytuly** [uber/h3-py#172]
is it possible building wheels for alpine linux? Who can answer to this question?

**Comment by ajfriend** [comment]
We use https://github.com/joerick/cibuildwheel to build the wheels. It builds a "`manylinux`" wheel, and my impression was that this should work on a variety of linux distributions. What's the exact issue with the current Linux wheels for Alpine?

**Comment by dfellis** [comment]
Alpine Linux doesn't use glibc as the base C library, it uses musl, and requires everything to be recompiled due to that difference.

But Alpine is quick to load and very small in disk usage, so it's popular in Docker containers.

**Comment by MuslimBeibytuly** [comment]
> We use https://github.com/joerick/cibuildwheel to build the wheels. It builds a "`manylinux`" wheel, and my impression was that this should work on a variety of linux distributions. What's the exact issue with the current Linux wheels for Alpine?

It doesn't use wheel, builds in docker
![image](https://user-images.githubusercontent.com/24839111/97989649-0ad1e980-1e09-11eb-8764-803d7e67a4fb.png)

**Comment by MuslimBeibytuly** [comment]
@ajfriend any updates on it?:)

**Comment by ajfriend** [comment]
Unfortunately, I don't have the Alpine Linux expertise to put this together. But if someone does want to take a stab, I'd be more than happy to merge a PR. :)

I'll close this for now, but anyone should feel to re-open if there are any new developments.
