### ISSUE TITLE
Bindings not recognised in PyCharm

### ISSUE THREAD

**Issue by jmccartin** [uber/h3-py#180]
On version 3.7.1, bindings such as geo_to_h3 (and others) are unrecognised by PyCharm and possibly other IDEs. This is happening after a fresh install via pip, and when used in the following manner:

```
import h3
h3.geo_to_h3(...)
```
Code appears to run fine however, so it's possibly the shared objects aren't being picked up properly. I've tried other endpoints and the same thing is happening with each of them.

**Comment by ajfriend** [comment]
Interesting. It would be great to have the library integrate well with IDEs. However, I'm not a PyCharm user. Do you know what interface PyCharm is expecting? If we can find some documentation on it, I can see what I can do about providing it in the library.

Off the top of my head, I would guess that it probably has something to do with the funky stuff I do to automatically generate the multiple APIs: https://github.com/uber/h3-py/blob/master/src/h3/api/_api_template.py

**Comment by jmccartin** [comment]
I'm not sure, although I tried to modify some of the imports in that file myself and I had no luck getting the endpoints to be recognised.

Do you accept pull requests? If I get some time I could try to experiment some more, maybe cross-check with something like VSCode, though I don't think PyCharm is doing anything non-standard here. H3 is the only library I have in my long list of dependencies that expresses this behaviour.

**Comment by ajfriend** [comment]
Definitely more than happy to accept a PR if you figure it out!

**Comment by kylebarron** [comment]
I've noticed this before with a non-Pycharm linting tool. I think the methods of having multiple dynamically-generated APIs messes with tools trying to follow imports. So for me `import h3.api.numpy_int` isn't able to be followed by my linter I think.
