### ISSUE TITLE
Working directly with bigint not supported

### ISSUE THREAD

**Issue by jakeatdrizly** [uber/h3-py#184]
The unsigned big ints are much leaner than the strings. Is there anything planned to support using H3 functions directly on the integers going forward?

e.g. h3.h3_to_parent(623560280962596863)

**Comment by ajfriend** [comment]
+1 to @kylebarron's comment.

I also recognize that these extra API's aren't documented super well (however, they are mentioned in the github readme!). We're working on documentation improvements, so hopefully these alternatives will be more obvious to folks.

**Comment by jakeatdrizly** [comment]
Thanks for the help Kyle, my fault for not reading the repo a little more closely.
