### ISSUE TITLE
PySpark UDF compatibility

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#186]
Moving this issue over from https://github.com/uber/h3/issues/457

This seems to have to do with PySpark serializing things for distribution across workers. I'm not familiar enough with PySpark to know off the top of my head what's happening and/or what the `h3-py` needs to provide for this to work properly.

We definitely want `h3-py` to be compatible with PySpark UDFs, but I think I would need some help from someone with more knowledge of what's going on from the PySpark side of things.

**Comment by ajfriend** [comment]
@isthegoal what version of `h3-py` are you using, and is it the same across the workers?

**Comment by jongbinjung** [comment]
Can't seem to reproduce. I suspect it's an environment setup issue? (e.g., wrong version of `h3` on executors)

```python
In [4]: from pyspark.sql.types import StringType
   ...: from pyspark.sql.functions import col, udf
   ...: import h3
   ...:
   ...: def get_h3_8_code(h3_code):
   ...:     return h3.h3_to_parent(h3_code, 8)
   ...:
   ...: get_h3_8_code_udf = udf(get_h3_8_code, StringType())
   ...:
   ...: df = spark.createDataFrame([('test', '8d418279112317f')], schema='name string, h3_code string')
   ...:
   ...: df.withColumn('h3_8_code', get_h3_8_code_udf(col('h3_code'))).collect()
   ...:
   ...:
Out[4]: [Row(name='test', h3_code='8d418279112317f', h3_8_code='8841827911fffff')]
```

**Comment by ajfriend** [comment]
I'll close this for now. @isthegoal, feel free to reopen if you have remaining questions.
