### ISSUE TITLE
python 2.7 support for h3

### ISSUE THREAD

**Issue by SaveTheRbtz** [uber/h3-py#19]
Currently setup.py is using Python3.5 api `subprocess.run`, which causes h3 installation to fail on python2 with:
```
    File "/tmp/vpip-build-h3-0.0.0-py2.py3-none-any.whl/h3/setup.py", line 15, in install_h3
      subprocess.run(
  AttributeError: 'module' object has no attribute 'run'
  Running setup.py bdist_wheel for h3: finished with status 'error'
```

Is it possible to make h3 python 2.7 compatible(at least until the official Python 2 deprecation in 2020)?

**Comment by TengHu** [comment]
This should fix that.
https://github.com/uber/h3-py/pull/25

**Comment by TengHu** [comment]
h3-py 3.4.1 released, should solve the compatibility issue. 

Thanks
