### ISSUE TITLE
macOS: h3-3.7.3 - Install - Could not build wheels for h3

### ISSUE THREAD

**Issue by billy-bligh** [uber/h3-py#219]
Collecting h3
  Using cached h3-3.7.3.tar.gz (17.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: h3
  Building wheel for h3 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for h3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [157 lines of output]
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 13.0.0.13000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_cmake_test_compile/build
      -- The C compiler identification is AppleClang 13.0.0.13000029
      -- The CXX compiler identification is AppleClang 13.0.0.13000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Warning at src/h3lib/CMakeLists.txt:278 (message):
        clang-format was not detected, so automatic source code reformatting is
        disabled
      
      
      CMake Warning at src/h3lib/CMakeLists.txt:290 (message):
        clang-tidy was not detected, so source code linting is disabled
      
      
      -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
      -- Found PythonInterp: /Library/Developer/CommandLineTools/usr/bin/python3 (found version "3.8.9")
      -- Found Cython: /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-build-env-rnie5r_a/overlay/bin/cython
      -- Found PythonLibs: libpython3.8.a
      -- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Failed
      -- Performing Test Weak Link MODULE -> SHARED (osx_dynamic_lookup) - Success
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      -- Configuring done
      CMake Warning (dev) at src/h3lib/CMakeLists.txt:214 (add_library):
        Policy CMP0115 is not set: Source file extensions must be explicit.  Run
        "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.
      
        File:
      
          /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/src/h3lib/src/h3lib/include/h3api.h.in
      Call Stack (most recent call first):
        src/h3lib/CMakeLists.txt:255 (add_h3_library)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          SKBUILD
      
      
      -- Build files have been written to: /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_skbuild/macosx-11.0-arm64-3.8/cmake-build
      [  2%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/algos.c.o
      [  5%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/coordijk.c.o
      [  8%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/bbox.c.o
      [ 11%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/polygon.c.o
      [ 14%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/h3Index.c.o
      [ 17%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/vec2d.c.o
      [ 20%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/vec3d.c.o
      [ 22%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/vertex.c.o
      [ 25%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/linkedGeo.c.o
      [ 28%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/localij.c.o
      [ 31%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/geoCoord.c.o
      [ 34%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/h3UniEdge.c.o
      [ 37%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/mathExtensions.c.o
      [ 40%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/vertexGraph.c.o
      [ 42%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/faceijk.c.o
      [ 45%] Building C object src/h3lib/CMakeFiles/h3.dir/src/h3lib/lib/baseCells.c.o
      [ 48%] Linking C static library lib/libh3.a
      [ 48%] Built target h3
      [ 51%] Generating C source src/h3/_cy/util.c
      [ 54%] Building C object src/h3/_cy/CMakeFiles/util.dir/util.c.o
      /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_skbuild/macosx-11.0-arm64-3.8/cmake-build/src/h3/_cy/util.c:6:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      make[2]: *** [src/h3/_cy/CMakeFiles/util.dir/util.c.o] Error 1
      make[1]: *** [src/h3/_cy/CMakeFiles/util.dir/all] Error 2
      make: *** [all] Error 2
        File "/private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-build-env-rnie5r_a/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 595, in setup
          cmkr.make(make_args, env=env)
        File "/private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-build-env-rnie5r_a/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 609, in make
          raise SKBuildError(
      
      
      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_skbuild/macosx-11.0-arm64-3.8/cmake-build
        Command:
          cmake /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_skbuild/macosx-11.0-arm64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.8.9 -DPYTHON_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -DPYTHON_LIBRARY:FILEPATH=libpython3.8.a -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-build-env-rnie5r_a/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=11.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      
      Traceback (most recent call last):
      
      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Source directory:
          /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc
        Working directory:
          /private/var/folders/n2/v113ybr521q5rdsyz28zxs580000gn/T/pip-install-hynomiht/h3_407c794a04634a508bfbbdbd74f3a9dc/_skbuild/macosx-11.0-arm64-3.8/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
Failed to build h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects

**Comment by kylebarron** [comment]
> macosx-11.0-arm64-3.8

I don't believe wheels are provided yet for Apple Silicon. See https://github.com/uber/h3-py/issues/204, https://github.com/uber/h3-py/issues/190. You might want to follow the dev notes to build from source: https://github.com/uber/h3-py/blob/master/dev_notes.md
