### ISSUE TITLE
h3 python on windows,  C library builds, h3-py may not be supported?

### ISSUE THREAD

**Issue by apiszcz** [uber/h3-py#27]
- The H3 C library using VS2017 created all .exes and appears to function. 
- However h3-py appears to be MacOS and LINUX only based on the package_data from setup.py below?
- Is there support for h3-py on windows or is it likely in the future?

Thank you

```
    package_data={
        'h-py':
        ['out/*.dylib' if platform.system() == 'Darwin' else 'out/*.so.*']
    },
```

**Comment by isaacbrodsky** [comment]
H3-py currently does not support Windows, but this is a planned improvement. I'm going to close this ticket to help centralize discussion of Windows support in #32 (There's also #18 but that's about GCC and I'm not sure it will be fixed at the same time.)
