### ISSUE TITLE
Possible bug in polyfill/polygon_to_cells when the polygon wraps over the North Pole

### ISSUE THREAD

**Issue by gwerbin-tive** [uber/h3-py#285]
I am unsure if this is a bug, or a known limitation, or user error. My apologies if it's the latter!

I used `h3.polyfill` to fill a polygon that wraps over the North Pole, but I found that it instead filled half of the "outside" of the polygon (I assume it only filled half because of https://github.com/uber/h3-py/issues/206).

I expected it to look like this: https://pictshare.net/4jxrmu.png

But it actually looked like this: https://pictshare.net/xa6fs7.png

Here is the code to reproduce the incorrect plot: https://gist.github.com/gwerbin-tive/d5fb24b1d7b9ee6ff10abe8d7d734b46

In order to produce the "expected" correct plot, change `radius = 1_000.0 + (5.5 * avg_edge_length)` to `radius = 1_000.0 + (5.0 * avg_edge_length)`. This make the radius small enough that the polygon no longer wraps over the North Pole.

If this is expected behavior, is there an "official" recommended workaround? Or am I just doing something wrong here?

Apologies if this issue belongs on the H3 core library issue tracker. I am reporting it here because I have only reproduced it in Python.

Thank you!

**Comment by nrabinowitz** [comment]
This is a core H3 issue - at present, our `polyfill`/`polygon_to_cells` logic uses Cartesian polygons, not spherical polygons, so it's generally going to struggle with a polygon that contains a pole. Adding to this is the issue in #206 - we assume the smaller polygon when some of the arcs are greater than 180 degrees, which is frequently the case very near the poles.

I think the best workaround here is to slice up polygons that contain a pole. I think the simplest version of this, which _ought_ to work (haven't tested yet) is to make triangles, one for each pair of vertexes, with the third vertex being the pole itself.

**Comment by nrabinowitz** [comment]
Yes, that was exactly the idea :). I have an example in JS here, but the rendering isn't great so you can't actually tell it's working: https://observablehq.com/@nrabinowitz/h3-polar-issues-with-polgon-to-cells

The main thing we check in the library is whether you have arcs that cross > 180 degrees of longitude. So as long as two vertices aren't further apart than that, you should be okay. You may need to move the longitude of the polar coordinate around to avoid a false positive there.
