### ISSUE TITLE
cells_to_multi_polygon

### ISSUE THREAD

**Issue by sandgrules** [uber/h3-py#290]
I'm trying to call h3.cells_to_multi_polygon(), but getting the error: 
AttributeError: module 'h3' has no attribute 'cells_to_multi_polygon'

Maybe I'm just doing something wrong? The rest of my tests have been successful, though. Running ver h3-4.0.0b1

**Comment by kylebarron** [comment]
Looks like the python api is `cells_to_polygons` instead?
https://github.com/uber/h3-py/blob/2b7ac39aa74c672ca3ca7e1d33eb32ff85831aba/src/h3/api/_api_template.py#L438-L465

**Comment by sandgrules** [comment]
I was  trying to locally update the example jupyter notebook (https://github.com/uber/h3-py-notebooks/blob/master/notebooks/usage.ipynb), but the line  polygons = h3.h3_set_to_multi_polygon([hex], geo_json=False) no longer works. In the migration guide, it has that h3SetToMultiPolygon was changed to cellsToMultiPolygon, but under notes it says 'bindings only'. Is this function no longer available in the Python API?

**Comment by kylebarron** [comment]
You should try the `cells_to_polygons` API above

**Comment by 1papaya** [comment]
Looks like at some point this function was dropped from the Python API, though [the docs suggest it should still exist](https://h3geo.org/docs/api/regions/). `4.0.0b1` doesn't have it though past versions still seem to; I installed `h3==3.6.1` which still includes the function `h3.h3_set_to_multi_polygon` and works just fine.

**Comment by agstnrdz** [comment]
i'm trying to practice the h3 python example by copying all the codes into my console and i am getting errors with the ```h3.set_to_multu_polygon``` function, i have also had errors in the past because they seem to have changed the syntax of some functions and i have found some solutions on forums. how can i get this to work?

**Comment by ajfriend** [comment]
> i'm trying to practice the h3 python example

What example are you looking at?

> i have also had errors in the past because they seem to have changed the syntax of some functions

We have! v4 has new function names, different from v3. If you're interested in polygon operations, check out https://uber.github.io/h3-py/polygon_tutorial.html. The full v4 API can be seen here: https://uber.github.io/h3-py/api_quick.html

**Comment by ajfriend** [comment]
I'm going to close this for now, but feel free to reach out if you have any additional questions. :)
