### ISSUE TITLE
module 'h3' has no attribute 'latlng_to_cell'

### ISSUE THREAD

**Issue by majbc1999** [uber/h3-py#292]
This simple code
```python
import h3

a = h3.latlng_to_cell(40.4083, -3.7011, 9)
```
returns:
`AttributeError: module 'h3' has no attribute 'latlng_to_cell'`

I tried installing h3-py via pip and conda, none works. Let me mention, that other APIs work just fine, for example `h3.polyfill(geoJson, 9)`  works well and returns expected results.

**Comment by kylebarron** [comment]
That's the v4 API but you have v3 installed. Use
```
pip install -U --pre h3
```
to install the v4 Python beta
