### ISSUE TITLE
Are there plans to make the new v4.0.0 work with Python3.11?

### ISSUE THREAD

**Issue by mborus** [uber/h3-py#293]
Since Python3.11 is now out as a stable release:
Will the v4.0.0 version, when it leaves beta, also be installable via pip
on this version of Python?

**Comment by kylebarron** [comment]
I'd argue we should have a 3.x patch release to add wheels for Python 3.11, but we should definitely add 3.11 to the wheel matrix as well. I think it's as easy as updating the cibuildwheel version

**Comment by nhoover** [comment]
I would appreciate being able to use python 3.11 with my app which doesn't currently work due to h3 not building (pip, Windows 10).

**Comment by ajfriend** [comment]
Starting on it here: https://github.com/uber/h3-py/pull/297

**Comment by ajfriend** [comment]
I'd support a 3.x patch for py 3.11. Pull requests welcome. I can also try it after updating the 4.0 branch.

**Comment by ajfriend** [comment]
Both the 3.7 and 4.0 branches have wheels for py 3.11:

- https://github.com/uber/h3-py/releases/tag/v3.7.6
- https://github.com/uber/h3-py/releases/tag/v4.0.0b2
