### ISSUE TITLE
Unable to use h3.latlng_to_cell()

### ISSUE THREAD

**Issue by paws07** [uber/h3-py#296]
>> h3.versions()
{'c': '3.6.3', 'python': '3.6.1'}
>> h3.latlng_to_cell(lat, lng, resolution)

AttributeError                            Traceback (most recent call last)
<ipython-input-14-111f8ba7424a> in <module>
----> 1 h3.latlng_to_cell(lat, lng, resolution)

AttributeError: module 'h3' has no attribute 'latlng_to_cell'

**Comment by ajfriend** [comment]
`latlng_to_cell` is the new 4.0 function name. See the summary of name changes here: https://h3geo.org/docs/library/migration-3.x/functions

On 3.x, the function name would be `geo_to_h3`.
