### ISSUE TITLE
Module 'h3' has no attribute 'cell_to_latlng'

### ISSUE THREAD

**Issue by AdelinaK** [uber/h3-py#310]
Hi. I used `pip install h3` and I wanted to extract the center of a grid to lat, long coordinates. I have this issue: module 'h3' has no attribute 'cell_to_latlng'. I read the documentation and in the test examples it is used as simple as `result = h3.cell_to_latlng(grid)`. 

The code snippet is very simple:
`import h3`
`h = '8928308280fffff'`
`result = h3.cell_to_latlng(h)`

What I am doing wrong? Thanks!

**Comment by AdelinaK** [comment]
Apparently the new function name is` h3.h3_to_geo`.

**Comment by nrabinowitz** [comment]
To be clear: The _old_ v3 function name is `h3_to_geo`, the _new_ v4 name is `cell_to_latlng`. But version 4 of `h3-py` is still only available as a beta release.
