### ISSUE TITLE
Why don't you expose gridDisk?

### ISSUE THREAD

**Issue by meyerovb** [uber/h3-py#314]
I'm trying to find places from a list of coordinates within x miles of each other... how am I supposed to do that without gridDisk?

**Comment by ajfriend** [comment]
`grid_disk` is available in the `h3-py` v4 beta release: https://uber.github.io/h3-py/api_reference.html#h3.grid_disk
You can install the beta with `pip install 'h3==4.0.0b2'`

For v3.7, the same function is named `k_ring`. See the function name translation table here: https://h3geo.org/docs/library/migration-3.x/functions
