### ISSUE TITLE
Support Python version 3.12

### ISSUE THREAD

**Issue by josteinl** [uber/h3-py#342]
Add support for Python version 3.12 would be much appreciated. 

Think this is somewhat relevant for #326.

**Comment by msaecker** [comment]
I tried my hand at extending the build pipeline to create python 3.12 wheels https://github.com/uber/h3-py/pull/344

**Comment by mborus** [comment]
> I tried my hand at extending the build pipeline to create python 3.12 wheels #344

This is great news. Could you also consider having the pipeline created wheels uploaded to a folder in this repo? This would make it easier to download it for offline and see which wheels are available.

**Comment by msaecker** [comment]
> > I tried my hand at extending the build pipeline to create python 3.12 wheels #344
> 
> This is great news. Could you also consider having the pipeline created wheels uploaded to a folder in this repo? This would make it easier to download it for offline and see which wheels are available.

Sorry, I wanted to do a minimal change to support python 3.12 and already had to include a few other commits because the v3 branch basically was unmaintained since the last release. This is a decision for the project owners.

**Comment by ajfriend** [comment]
@josteinl, have you tried the v4 beta on 3.12 (`pip install 'h3==4.0.0b4'`)?

**Comment by josteinl** [comment]
> @josteinl, have you tried the v4 beta on 3.12 (`pip install 'h3==4.0.0b4'`)?

I'm affraid not, but thank you for your notice.

**Comment by ajfriend** [comment]
OK. I'll close this for now then. Please let us know if you have any issues with 3.12 on either v3.7 or v4.0
