### ISSUE TITLE
Support Python version 4.1

### ISSUE THREAD

**Issue by rafajm7** [uber/h3-py#345]
Is there a planned release date for 4.1.0 Python bindings?

H3 has announced that version 3 is not supported anymore. 

Thanks for your help!

**Comment by ajfriend** [comment]
h3-py v4.0 should be released soon. If you haven't already, please try the beta releases and let us know if you have any issues.

After releasing v4.0, we can pretty quickly bump it up to v4.1

**Comment by ajfriend** [comment]
This should be done with the new release. Let me know if you have any issues.
