### ISSUE TITLE
Move cython test to its own folder

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#346]
Move `test_cython.py` and `cython_example.pyx` to a separate folder.

**Comment by I3lackRacer** [comment]
I would do that. Can you assign me the issue?

**Comment by ajfriend** [comment]
Awesome. Thanks!

**Comment by ajfriend** [comment]
I was imagining just a separate folder like `test/cython/`

**Comment by I3lackRacer** [comment]
Alright, I will change that

**Comment by ajfriend** [comment]
Your version is fine :)
