### ISSUE TITLE
Unexpected Behavior with Multipolygons of Certain Seas in H3 Library (v4.0.0b2)

### ISSUE THREAD

**Issue by sawadogosalif** [uber/h3-py#353]
When using h3.geo_to_cells  and h3.cells_to_h3shape to create hexagons and geometry for certain seas, such as the Chukchi Sea, Nord Atlantic Ocean, South Atlantic Ocean, South Pacific Ocean, and North Pacific Ocean, unexpected results occur with the H3 library.

Seeking assistance from the community or developers to help. Any insights or suggestions would be greatly appreciated.

Below is the details of my code:
Library Version: Using H3 version 4.0.0b2.
For example, the coordinates for the Chukchi Sea vary between -180 and -155 for longitudes, and between 175 and 180. 
``` python
import geopandas as gpd
data = gpd.read_file(r"Shapefile\World_Seas_IHO_v1\World_Seas.shp")
tmp = data[data.NAME.isin(["Chukchi Sea"])]
tmp.plot(figsize=(20,100))
```

![image](https://github.com/uber/h3-py/assets/96554481/0b70db40-266b-4899-b9cf-3a813328068e)
 

After transformation, the longitudes seem to fluctuate between -180 and 180, leading to erroneous results.
I use the code below
```python
import h3
#all geos in a GeoDataFrame to cell
cell_column = tmp.geometry.apply(lambda x: h3.geo_to_cells(x, res=4))
# Converting cells to geo objects
shape_column = cell_column.apply(h3.cells_to_h3shape)
tmp.geometry = shape_column
tmp.plot(figsize=(10,100))
```
![image](https://github.com/uber/h3-py/assets/96554481/7c3166d8-6a2d-4151-8c07-f5984c1124b5)

**Comment by sawadogosalif** [comment]
@ajfriend I follow your recent tutorial on h3

**Comment by ajfriend** [comment]
Thanks for the report @sawadogosalif, and I really appreciate you testing out the beta!

Could you try with the recent 4.0.0b3 version and see if you still have the issue?

**Comment by isaacbrodsky** [comment]
From an initial look at this, I think it could be the same issue as https://github.com/uber/h3-js/issues/158#issuecomment-1244087555 This may be a bug in how the cell boundaries are being plotted that doesn't reflect a bug in the coordinates themselves?

**Comment by sawadogosalif** [comment]
I still have the same issue with 4.0.0b3. I am using data from https://www.marineregions.org/download_file.php?name=World_Seas_IHO_v1.zip. Unfortunately, there is no GeoJSON format available. I am also using GeoPandas 0.14.3. @ajfriend

**Comment by timgilbertson-os** [comment]
This is an expected matplotlib artifact, not H3.

**Comment by nrabinowitz** [comment]
Agree, this is a rendering problem, not a bug in the library. H3 always outputs coordinates in the -180 - 180 range, so some renderers (particularly those expecting Cartesian, rather than spherical, coordinates) will have trouble rendering these shapes. To fix, you need to adjust all longitude coords on either the positive or negative side of the range so that all values are either positive or negative.
