### ISSUE TITLE
polyfill - how to get all intersected h3 polygons 

### ISSUE THREAD

**Issue by Donglai-Zhang-asurion** [uber/h3-py#354]
Looks polyfill takes geojson to break into all h3 polygons which center's coordinates are in given geojson polygon.  
Is there anyway to get all intersected h3 polygons from the given geojson?

**Comment by nrabinowitz** [comment]
This functionality is now in the core library, but hasn't been released yet - see https://github.com/uber/h3/pull/796 . We hope to release this in the near future.

**Comment by Donglai-Zhang-asurion** [comment]
Thank you. i guess there is a few months needed to have it in `h3-py`. 
In my current usecase, these process may work : 
1. breaking down geojson to h3 cells 
2. find out all unique neighbor cells
3. get overlapped all these extra neighbor cells by checking if overlapping with given geometry. 
> This functionality is now in the core library, but hasn't been released yet - see [uber/h3#796](https://github.com/uber/h3/pull/796) . We hope to release this in the near future.

**Comment by nrabinowitz** [comment]
> Thank you. i guess there is a few months needed to have it in `h3-py`. In my current usecase, these process may work :
> 
> 1. breaking down geojson to h3 cells
> 2. find out all unique neighbor cells
> 3. get overlapped all these extra neighbor cells by checking if overlapping with given geometry.

This will work in general, but there may be edge cases where it does not work. For example, if you polyfill a very long, very narrow polygon you may only get a few cells, or no cells, but many cells beyond immediate neighbors would intersect. In general you likely need to trace the edges of the polygon, find all cells along these edges plus their immediate neighbors, and check each of these for intersection as well as the interior cells returned from the polyfill.

**Comment by Donglai-Zhang-asurion** [comment]
@nrabinowitz, thank you again for pointing it out. 
Got it - recursively looking for and check intersection on the neighbors through tracing the edges can cover it, and requires a little more dev work than i thought. - will go this way for now. 

BTW, wish the new version will go alive soon

> > Thank you. i guess there is a few months needed to have it in `h3-py`. In my current usecase, these process may work :
> > 
> > 1. breaking down geojson to h3 cells
> > 2. find out all unique neighbor cells
> > 3. get overlapped all these extra neighbor cells by checking if overlapping with given geometry.
> 
> This will work in general, but there may be edge cases where it does not work. For example, if you polyfill a very long, very narrow polygon you may only get a few cells, or no cells, but many cells beyond immediate neighbors would intersect. In general you likely need to trace the edges of the polygon, find all cells along these edges plus their immediate neighbors, and check each of these for intersection as well as the interior cells returned from the polyfill.

**Comment by ajfriend** [comment]
Glad you got it working @Donglai-Zhang-asurion!

h3-py v4.0 should be released soon, and it should be quick to add https://github.com/uber/h3/pull/796 once that is released in the core C library.
