### ISSUE TITLE
Cannot use H3Poly to generate polygons

### ISSUE THREAD

**Issue by wanthons** [uber/h3-py#367]
Hi there! I'm trying to use H3 to create a polygon border on a map but I'm having trouble getting it to work.

The main issue right now is that I can't seem to access the 'H3Poly' attribute. Running the polygon tutorial code from the website (https://uber.github.io/h3-py/polygon_tutorial.html) results in the following error:
```
# Excerpt from the tutorial code
outer = [
    (37.804, -122.412),
    (37.778, -122.507),
    (37.733, -122.501)
]
poly = h3.H3Poly(outer)
print(poly)
plot_shape(poly)
```
> AttributeError: module 'h3' has no attribute 'H3Poly'

I'm not using Anaconda and installed the module simply by using `pip install h3`, so I'm not sure whether I'm missing any dependencies to get it working properly.

I'm new to Python so if I'm missing something, any tips or help would be very much appreciated.

Thanks!

**Comment by ajfriend** [comment]
You need to ensure you are running the v4.0 beta version, which you can check with `h3.versions()`. What output do you get when you run that function?

**Comment by wanthons** [comment]
Ah! Yeah, I was running the main H3 version on PyPI which was v3.7.7, I didn't realize that h3.Polygon() was only added after v4.0. Works perfectly fine now after I re-installed using `pip install h3 --pre`

Thanks for the help and your work on the package!
