### ISSUE TITLE
"geo_to_h3" and "h3_to_parent" return different values.

### ISSUE THREAD

**Issue by kato1208** [uber/h3-py#369]
I found a case where "geo_to_h3" and "h3_to_parent" return different values. Why does this happen?

```python
import h3.api.basic_int as h3

lat = 53.3979685
lon = 10.9781757
resmin = 5
resmax = 9

cell = h3.geo_to_h3(lat, lon, resmax)
cells = [cell]
for res in range(resmax-1, resmin-1, -1):
    cell = h3.h3_to_parent(cell, res)
    cells.append(cell)
cells.reverse()
print(cells)

print([
    h3.geo_to_h3(lat, lon, 5),
    h3.geo_to_h3(lat, lon, 6),
    h3.geo_to_h3(lat, lon, 7),
    h3.geo_to_h3(lat, lon, 8),
    h3.geo_to_h3(lat, lon, 9),
])
```
```
[599524248867831807, 604027847824113663, 608531447367598079, 613035046992871423, 617538646618406911]
[599524264973959167, 604027847824113663, 608531447367598079, 613035046992871423, 617538646618406911]
```
Version
```
pip3 freeze | grep h3
h3==3.7.7
```

**Comment by dfellis** [comment]
So, when you index a coordinate to an H3 cell at a specified resolution, it confirms exact containment of the coordinate within the cell. Meanwhile the parent-child relationship is a hierarchical tree structure (where each hexagon has 7 child hexagons and each pentagon has 5 child hexagons and 1 child pentagon), but you can't tile a hexagon with hexagons perfectly, so the parent-child relationship is only partially correct.

[@nrabinowitz has a good explainer on this approximation](https://observablehq.com/@nrabinowitz/h3-hierarchical-non-containment)

**Comment by kato1208** [comment]
Thank you very much. It was really easy to understand!
