### ISSUE TITLE
Generate hexagons over areas not entirely within a polygon?

### ISSUE THREAD

**Issue by marklit** [uber/h3-py#379]
I want to generate H3s for the coastal areas as well as anything inland. With `h3.LatLngPoly` it only wants to generate hexagons that are entirely in land and miss areas like Miami for example. Any idea how I could do this?

<img width="856" alt="qgis-bin_0RQJmFLOPZ" src="https://github.com/uber/h3-py/assets/359316/729e191a-0b63-4bf0-8cb0-bc28286159d7">

Here's the code that I have atm:

```bash
$ wget https://raw.githubusercontent.com/scdoshi/us-geojson/master/geojson/nation/US.geojson
```

```python
import geopandas as gpd
import h3


print(h3.versions()) # {'c': '4.0.0', 'python': '4.0.0b5'}

usa = gpd.read_file('US.geojson')
polygons = list(list(x.geoms) for x in usa.geometry)[0]

polygons.sort(key=lambda x: x.area)
coords = polygons[-1].exterior.coords[:]
coords = list(c[:2][::-1] for c in coords)

poly = h3.LatLngPoly(coords)

h3_list = set(h3.h3shape_to_cells(poly, res=3))
```

**Comment by grim7reaper** [comment]
I think it's now possible to do that with the H3 C library, but it's not yet exposed in `h3-py` IIUC.

Meanwhile you could try [h3ronpy](https://github.com/nmandery/h3ronpy?tab=readme-ov-file), with `ContainmentMode=IntersectsBoundary` (or `Cover`) it should do the trick.
Cf. example [here](https://h3ronpy.readthedocs.io/en/latest/usage/vector.html#polygon-fill-modes).

**Comment by marklit** [comment]
Thanks for that.
