### ISSUE TITLE
Find Codecov alternative

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#393]
Codecov seems to be broken, as in https://github.com/uber/h3-py/pull/389

**Comment by ajfriend** [comment]
A possible alternative: https://hynek.me/articles/ditch-codecov-python/

**Comment by ajfriend** [comment]
Weird. Codecov is working again? https://github.com/uber/h3-py/pull/394

**Comment by ajfriend** [comment]
As noted in https://github.com/uber/h3-py/pull/408, this seems to be a known issue with Codecov and it doesn't look like it will be resolved any time soon:

- https://github.com/codecov/codecov-action/issues/29
- https://github.com/pypa/twine/issues/658

Let's find an alternative solution.

**Comment by jongbinjung** [comment]
Going to mark closed, by #413 

We can re-open if we decide otherwise.
