### ISSUE TITLE
New behaviour porting from polyfill to polygon

### ISSUE THREAD

**Issue by fhk** [uber/h3-py#395]
Looks like docs are abit scarce on the ground and its hard to go between versions.

Is there a like for like replacement for polyfill?

Here is a current method that seems cumbersome.

```python
    # Convert GeoDataFrame geos to h3 cells
    gdf['h3s'] = pd.Series([h3.geo_to_cells(geom, res=8) for geom in gdf.geometry])
    gdf = gdf.explode('h3s')
    cell_column = gdf.h3s.apply(lambda x: [x])
    shape_column = cell_column.apply(lambda x: h3.cells_to_h3shape(x))
    gdf.geometry = shape_column
```

**Comment by dfellis** [comment]
The replacement for `polyfill` is [`polygon_to_cells`](https://h3geo.org/docs/api/regions#polygontocells). Currently behaves identically to `polyfill` but work is being done to add different fill options.

**Comment by dfellis** [comment]
That should not be the case. [Looking at the cython bindings](https://github.com/uber/h3-py/blob/cec946a879eb7706e41a0526752dd688c6e56fd5/src/h3/_cy/latlng.pyx#L127-L172) it doesn't add any extra logic versus the C code.

Can I see some example code that misbehaves?

**Comment by fhk** [comment]
Sure

```python

    gdf = gpd.GeoDataFrame([[1, Point(0., 0.)]], columns=['id', 'geometry'], geometry='geometry', crs='EPSG:4326')
    gdf = gdf.to_crs('EPSG:3857')
    gdf['geometry'] = gdf.geometry.buffer(2000)
    gdf = gdf.to_crs('EPSG:4326')
    # Convert GeoDataFrame geos to h3 cells
    gdf['h3s'] = pd.Series([h3.geo_to_cells(geom, res=8) for geom in gdf.geometry])
    #gdf = gdf.explode('h3s')
    #cell_column = gdf.h3s.

apply(lambda x: [x])
    shape_column = gdf.h3s.apply(lambda x: h3.cells_to_h3shape(x))
    gdf.geometry = shape_column
 ```
 
 ![Screenshot 2024-09-04 at 10 27 41 AM](https://github.com/user-attachments/assets/a368e3cf-c4c3-40a1-a297-4d48145ef997)

**Comment by fhk** [comment]
Not sure what the recommended way to go from is:

polygon --> h3s --> h3 geoms

**Comment by dfellis** [comment]
So looking at this part of the code:

```py
 gdf = gpd.GeoDataFrame([[1, Point(0., 0.)]], columns=['id', 'geometry'], geometry='geometry', crs='EPSG:4326')
    gdf = gdf.to_crs('EPSG:3857')
    gdf['geometry'] = gdf.geometry.buffer(2000)
    gdf = gdf.to_crs('EPSG:4326')
```

I don't see how a hole in the geometry could be created by this? It looks like it should be trying to create a circle, I think?

This part then generates cells at res 8:

```py
gdf['h3s'] = pd.Series([h3.geo_to_cells(geom, res=8) for geom in gdf.geometry])
```

And then this line converts the set of cells into an outline of the cells to show as a polygon

```py
shape_column = gdf.h3s.apply(lambda x: h3.cells_to_h3shape(x))
```

I *think* you need to pass the [`axis=1` parameter](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html) for it to generate a separate outline for each hexagon?

**Comment by fhk** [comment]
hmmm this gives the same result

```python
shape_column = gdf.apply(lambda x: h3.cells_to_h3shape(x.h3s), axis=1)
```

**Comment by fhk** [comment]
> I don't see how a hole in the geometry could be created by this? It looks like it should be trying to create a circle, I think?

yes sorry I'm am not seeing issues with holes apologies

**Comment by dfellis** [comment]
Sorry, was at lunch when you sent that. The documentation is saying that it tries to send full rows or columns to you to operate on. Perhaps you can rewrite it as:

```py
shape_column = gdf.apply(lambda xs: [h3.cells_to_h3shape([x]) for x in xs.h3s)
```

to force it to operate on a per cell basis?

But I'll note that I don't think this is an issue with h3-py itself, but rather the behavior of the dataframe library.

**Comment by ajfriend** [comment]
@fhk Thanks for the questions! We're still in 4.0 beta and can thus make changes, so I'm definitely looking for general feedback on the API, documentation, and any suggestions on what might be more ergonomic. By the way, have you seen the Polygon Tutorial, specifically the section on working with geopandas: https://uber.github.io/h3-py/polygon_tutorial.html#interfacing-with-geopandas-and-other-libraries ?

In this question specifically, if I'm understanding correctly, what you're looking for is to get collections of individual H3 cells, but `h3.cells_to_h3shape` provides the outline of the set of cells. Do I have that right?

The reason `h3.cells_to_h3shape` returns the outline is that I usually think of sets of H3 cells as representing some area like a GeoJSON Polygon or MultiPolygon, and I care about the **area represented by those cells** more than the individual cells themselves (usually, at least). And when trying to represent a MultiPolygon with H3 cells of some resolution, a common question is how much approximation error results from that representation. One way to answer that is to compare the before and after outlines, like:

<img width="995" alt="image" src="https://github.com/user-attachments/assets/e1c1a422-9268-4074-9c63-b8a3763135e0">

So, I think the outline is a pretty natural default output when considering a set of H3 cells, but there are also situations where you'd want the individual cells. You can achieve that with the current API with a little work, but its fair to consider if it would be worth adding something in the API to make that easier.

I'll add a notebook on how to do this shortly. Beyond that, I'd be interested in your thoughts on:

- Does the https://uber.github.io/h3-py/polygon_tutorial.html cover this sufficiently, or do we need to add to the documentation?
- Would additional API functions be helpful, or is it sufficient to have explain how to do it in the docs with the current API?
- What would your ideal H3 API look like for the type of work you're currently doing?

**Comment by ajfriend** [comment]
https://gist.github.com/ajfriend/cba80a79d0be223cc40b3d35aa8e4e27

**Comment by fhk** [comment]
> have you seen the Polygon Tutorial, specifically the section on working with geopandas: [](https://uber.github.io/h3-py/polygon_tutorial.html#interfacing-with-geopandas-and-other-libraries)

Oh nice ! this is new to me. Looks like it covers some of the gap.

> but there are also situations where you'd want the individual cells.

Yes the main one being to merge with other data sets, e.g. https://pysal.org/tobler/notebooks/census_to_hexgrid.html



> * Does the https://uber.github.io/h3-py/polygon_tutorial.html cover this sufficiently, or do we need to add to the documentation?

I think its a start, the main question is around the expected/recommended path for:

1. Shapely --> h3 --> Shapely
2. Geopandas --> h3 --> Geopandas

Then this also needs to consider the performance aspect. Doing a bunch of apply and list comps can take a hit in classic pandas trade-off. I find myself reaching for the DuckDB interface...

Not sure what the performance expectation is around creating the indexes in polygons but typically I'd use some kind of point sampling rather that this if there is a data set like buildings and it covers most of the region...


> * Would additional API functions be helpful, or is it sufficient to have explain how to do it in the docs with the current API?

I think its OK at the moment, but I haven't benchmarked it...


> * What would your ideal H3 API look like for the type of work you're currently doing?

This probably requires more thought from my side. But typically it's trying to combine 4+ layers across different geometry types and attributes.

One thing that would perhaps be nice is to flip the model. Rather than apply h3s to everything can there be some object that ingests the data to a single index and you can then call the methods on it?

There are a bunch of operations where I'm joining by index and then taking k-ring and smoothing.

Then there's the quad tree style usecase too. Where you want to find the nearest neighbor that is in the data.

Perhaps its worth taking a review of where h3-py is being used and how then where/what could be in scope?
