### ISSUE TITLE
Install with google appengine

### ISSUE THREAD

**Issue by howardmalec** [uber/h3-py#40]
Do you have recommendations for installing cmake/cc/make for app engine? Wanted to run h3 on a flask web app and have been encountering issues related to the environment setup.

**Comment by howardmalec** [comment]
Ideally if you have a docker file you could point to? I'm struggling with setting up the binaries (cmake, make, cc). Thanks.

**Comment by isaacbrodsky** [comment]
If you are using Alpine or Debian you might be able to follow the instructions in uber/h3 for installing build dependencies to your container. (https://github.com/uber/h3#install-build-time-dependencies) You may also need to install `git` for h3-py to build.

**Comment by SteveAlexander** [comment]
I used the sister project `h3cy` in a Google Cloud Function, and it seems to be working fine.

To use it, I added 'h3cy>=0.0.3` in the `requirements.txt`

https://github.com/kwmsmith/h3-cython

I did take a look at using `h3-py`, but it seemed like a lot more work.

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully fix these install issues. Could you please try installing with `pip install h3==3.6.1` and let us know how it works?

I'll close this for now. Please re-open if the issue persists!

**Comment by irockafe** [comment]
Thanks for this! Updating to 3.6.1 fixed the "cmake required but not found" error when deploying to google app engine.
