### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#417]

**Comment by Pivert** [comment]
`Downloading h11-0.14.0-py3-none-any.whl (58 kB)
Building wheels for collected packages: timezonefinder, h3
  Building wheel for timezonefinder (pyproject.toml) ... done
  Created wheel for timezonefinder: filename=timezonefinder-6.5.3-cp313-cp313-manylinux_2_36_x86_64.whl size=50694848 sha256=e7276c9111cd1df6223b834c9d2453de5e38a2a245fc10f78afc96c170f2ae45
  Stored in directory: /user/.cache/pip/wheels/9d/c4/b1/1eb9571e2338f891681bfadb09b36b629c3ccb0bc4672a6d03
  Building wheel for h3 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for h3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.Not searching for unused variables given on the command line.
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------
      
                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.
      
                      Building Linux wheels for Python 3.13 requires a compiler (e.g gcc).
                It can be installed using debian package manager:
      
      sudo apt-get install build-essential
      
                To build compliant wheels, consider using the manylinux system described in PEP-513.
                Get it with "dockcross/manylinux-x64" docker image:
      
                  https://github.com/dockcross/dockcross#readme
      
                For more details, please refer to scikit-build documentation:
      
                  http://scikit-build.readthedocs.io/en/latest/generators.html#linux
      
                      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
Successfully built timezonefinder
Failed to build h3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (h3)
`

**Comment by ajfriend** [comment]
`h3-py` does currently work with 3.13, but we just didn't provide pre-built wheels for it.

This will happen any time a new version of Python comes out. Generally, I'd expect `h3-py` to work with any new version, but we probably won't have built wheels for that version. That's what you're running into here: you just need to install all the dependencies to build the wheel yourself for 3.13.

https://github.com/uber/h3-py/pull/425 will release a new version with pre-built wheels for 3.13

**Comment by ajfriend** [comment]
Closed with #425
