### ISSUE TITLE
`cell_to_boundary` function returning wrong Polygons

### ISSUE THREAD

**Issue by augustomarcolin** [uber/h3-py#424]
I'm using package version 4.1.1 and encountering issues with the `cell_to_boundary` function.

The problem is that it's returning an incorrect polygon for the given hash ID. Below is an example of the expected output versus what is being returned.

After some testing, I found that the issue seems to be with the latitude and longitude being inverted.

Example:
```python
import h3
from shapely.geometry import Polygon
h3.latlng_to_cell(-22.902, -47.068, 8)
Polygon(h3.cell_to_boundary("88a813b22bfffff")).wkt
```

- `h3.latlng_to_cell(-22.902, -47.068, 8)` -> returns `88a813b22bfffff`, which should correspond to an area near Campinas, Brazil.
- `h3.cell_to_boundary("88a813b22bfffff")` -> returns a polygon located in the middle of the ocean.

If you try inverting lat/lng, you have the right polygon location: 
```python
h3.latlng_to_cell(-47.068, -22.902, 8) #returns 88dceb3417fffff
Polygon(h3.cell_to_boundary("88dceb3417fffff")).wkt
```

**Comment by dfellis** [comment]
It's in the name, `latlng_to_cell` takes `lat`, then `lng`.

![Screenshot from 2024-10-24 16-54-03](https://github.com/user-attachments/assets/5b413110-9a94-4406-b445-73161a05534c)

Here's using the `h3-js` implementation and your example point produces the same hexagon ID:

![Screenshot from 2024-10-24 16-53-52](https://github.com/user-attachments/assets/9a2e4319-a04c-47ae-bf3c-6f6ef0ec8484)

When you invert it, you're calling it correctly. Your original point is [`lng, lat`, based on Google Maps taking it in that format and your description of where the point should be.](https://www.google.com/maps/place/22%C2%B054'07.2%22S+47%C2%B004'04.8%22W/@-22.901995,-47.0705749,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-22.902!4d-47.068?entry=ttu&g_ep=EgoyMDI0MTAyMy4wIKXMDSoASAFQAw%3D%3D)

**Comment by dfellis** [comment]
Sorry about that. Google Maps does lat, lng order and that's what you originally provided. I got myself confused there.

When I [insert the original H3 cell you provided into the `h3geo.org` website](https://h3geo.org/#hex=88a813b22bfffff) it renders in the correct place.

I now suspect that this line is at fault:

```py
Polygon(h3.cell_to_boundary("88a813b22bfffff")).wkt
```

GeoJSON requires points to be in `lng, lat` order while Google Maps and H3 uses `lat, lng` ordering by default.

@ajfriend has created an `h3shape` concept in the `h3-py` library to work with other libraries that use the `lng, lat` ordering by default.

If you replace that line above with

```py
Polygon(h3.cells_to_h3shape(["88a813b22bfffff"])).wkt
```

I think it should work as you expect it to.

**Comment by augustomarcolin** [comment]
Thanks for your quick response!

I tested the line you suggested, but the `Polygon` method isn’t compatible with the output format from `h3.cells_to_h3shape`.

Even without using `Polygon`, the behavior seems strange. Here’s what I get when I run:

```python
h3.cell_to_boundary("88a813b22bfffff")
```

The boundaries returned are:

```
((-22.90842596880987, -47.06731219632237),
 (-22.905535293101952, -47.063153899029516),
 (-22.900853775164972, -47.06403194446073),
 (-22.899063004789415, -47.06906819652065),
 (-22.901953757949865, -47.07322640494308),
 (-22.906635204022603, -47.07234845018628))
```

When I simulate these coordinates here: https://www.keene.edu/campus/maps/tool/, the issue persists. The location still appears in the middle of the ocean, haha. It looks like the function may be reversing the lat/lng order in the boundaries.
