### ISSUE TITLE
hexRangeDistances function in 4.x 

### ISSUE THREAD

**Issue by gherka** [uber/h3-py#430]
Are there plans to port the `hexRangeDistances` [function](https://h3geo.org/docs/3.x/api/traversal/#hexrangedistances) to the 4.x API? It's currently only available in 3.x. If not, are there alternative ways to achieve the same output?

**Comment by ajfriend** [comment]
Would something like this work for you?

```python
def grid_disk_distances(h, k):
    return [h3.grid_ring(h,i) for i in range(k)]
```

**Comment by ajfriend** [comment]
For the first, I think you want https://uber.github.io/h3-py/api_verbose.html#h3.cell_to_boundary

For the last two, check out:

- https://uber.github.io/h3-py/api_quick.html#polygon-interface
- https://uber.github.io/h3-py/polygon_tutorial.html

**Comment by ajfriend** [comment]
Closing for now. Let me know if you have any additional questions.
