### ISSUE TITLE
conda release

### ISSUE THREAD

**Issue by geoHeil** [uber/h3-py#48]
Hi,

I want to create a conda release for h3-py. But currently, struggle with the configuration of `cc`.

In case you can help out, please look at:
https://stackoverflow.com/questions/56341092

The recipe is found here: https://github.com/geoHeil/staged-recipes/blob/h3-py/recipes/h3/meta.yaml

When trying to execute a local build using:

`    /.circleci/run_docker_build.sh`
it fails with:

`    Unsatisfiable dependencies for platform linux-64: {'cc'}
`
Where the important part of the mata.yml looks like:

    ```
requirements:
      build:
        # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
        # Compilers are named 'c', 'cxx' and 'fortran'.
        - {{ compiler('c') }}
        - cmake
        - make
        - cc
      host:
        - python
        - pip
      run:
        - python
```

How can I get it to work to submit my first conda-forge package?

And when leaving `- cc` out:

```
    + command -v cc
      + echo 'cc required but not found.'
```
it fails as `cc` is not found.

**Comment by dfellis** [comment]
`cc` stands for "C Compiler" and is usually a symlink to the c compiler of the host Unix system, such as `gcc` or `clang` (or actually is the C compiler on really old unices), so this repository can compile with minimal effort on any of them.

Whatever conda is, it has broken that convention, so I'd bring it up with them.

A wild stab in the dark, though, is that if you simply add `- gcc` to your config, it will install gcc the "normal" way and set up a `cc` symlink for you and it'll work as desired. That might not be the case, but I think it would take more effort to break that behavior when installing gcc, so I'd at least give it a try?

**Comment by geoHeil** [comment]
I create a pull request there:
https://github.com/conda-forge/staged-recipes/pull/8467
When patching the build file this step works, but if fails during packaging as no output is found. Do you know more?

**Comment by geoHeil** [comment]
@dfellis I followed your suggestion:

```
failed
ERROR:conda.core.link:An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: ...working... done
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 1079, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "/opt/conda/lib/python3.7/site-packages/conda/gateways/subprocess.py", line 85, in subprocess_call
    output=formatted_output)
subprocess.CalledProcessError: Command '['bash', '/home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/.tmp8uauzadk']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 649, in _execute_post_link_actions
    activate=True)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 1095, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 558, in _execute
    cls._execute_post_link_actions(pkg_idx_tracked, axngroup)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 664, in _execute_post_link_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 121, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1361, in build
    create_build_envs(m, notest)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1249, in create_build_envs
    is_cross=m.is_cross, is_conda=m.name() == 'conda')
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 867, in create_env
    execute_actions(actions, index)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 320, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 532, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.7/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
    unlink_link_transaction.execute()
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 587, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>
```

but linking falis

**Comment by dfellis** [comment]
> failed
> ERROR:conda.core.link:An error occurred while installing package 'defaults::gcc-4.8.5-7'.
> LinkError: post-link script failed for package defaults::gcc-4.8.5-7
> running your command again with `-v` will provide additional information
> location of failed script: /home/conda/feedstock_root/build_artifacts/h3_1559102609599/_build_env/bin/.gcc-post-link.sh
> ==> script messages <==
> <None>

@geoHeil that's definitely an issue with this conda project you're working with. It can't install gcc at all despite supposedly having support to do so.

Also, the version of gcc it's trying to install is very old. [It was released nearly 4 years ago](https://gcc.gnu.org/releases.html) so I wonder if whatever mirror they're pulling gcc from simply dropped that version.

These are all definitely issues with conda that need to be worked out by them. Feel free to link this issue to their own issue tracker.

Finally, if you have some free time after reporting to the conda team about your issues, you could try replacing `- gcc` with `- clang` as maybe their source for clang is more up-to-date? (I read up a bit on conda in the meantime, and clang is better supported on MacOS, so they might be compiling all C code with clang everywhere instead of gcc and no one noticed the gcc issue because they're not using it?)

**Comment by geoHeil** [comment]
Adding `clang` to:
```
requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - clang
  run:
    - python
```

or 

```
requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - clang
  host:
    - python
    - pip
  run:
    - python
```

both fail with:
`conda.exceptions.ResolvePackageNotFound
`though it should be there: https://anaconda.org/anaconda/clang

Maybe it is using the wrong channel?

**Comment by isuruf** [comment]
@dfellis, is there a way to use an external `h3` package for `h3-py`? `h3` is now packaged in conda and `h3-py` needs to use that package instead of using the `install.sh` script.

**Comment by dfellis** [comment]
That seems like a tough problem. We could add some magic to the install.sh script to detect a system H3 C library and not compile its own, but I could also see some users not wanting that behavior (eg, they have an older version installed globally and they want a newer version in their virtualenv).

Looking at the help for `pip install`, it looks like the `--install-option` flag could be used here, so we could add a `--use-system-h3` flag for `setup.py` and conda could install the package with `pip install h3 --install-option="--use-system-h3=/path/to/h3"` to have it skip that and adjust the main `h3.py` file so it knows to load the SO file from that provided path.

This still seems like it would require a lot of testing/debugging to make sure it actually works correctly. I only help out with H3 in my spare time now that I'm no longer at Uber, so I don't know when I could try to tackle that issue, but that's my current thinking on how to solve the issue. @isaacbrodsky or @karentycoon might have a better idea on how to handle this, though.

**Comment by isaacbrodsky** [comment]
@ajfriend @TengHu Do you know if this would be effected by the port to Cython? If so, we might want to focus our work on that effort.

**Comment by jhagege** [comment]
+1

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully help with these install issues.

We have pre-built wheels available on PyPI with  `pip install h3==3.6.1`, but `conda` is a different story.

Would someone like to take a stab at a `conda` release? We can definitely help support that, now that we're on the new Cython wrapper.

**Comment by geoHeil** [comment]
The older versions were successfully ported to conda. However, with the latest changes https://github.com/conda-forge/h3-py-feedstock/pull/12 the test cases indicate that it is broken. @ajfriend do you think you could support in fixing the test cases for this new version so that we can push the updated release to conda?

**Comment by FenderJazz** [comment]
Apologies if this is the wrong thread, but I've had trouble with the conda pull today.

**Steps:**

conda install h3-py
...
  added / updated specs:
    - h3-py

The following NEW packages will be INSTALLED:

  h3                 conda-forge/win-64::h3-3.6.3-he025d50_0
  h3-py              conda-forge/win-64::h3-py-3.4.3-py38hc8b782b_4

**Problem:**

import h3
h3.geo_to_h3(56, 0, 15)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-9dc35713fa98> in <module>
      1 import h3
----> 2 h3.geo_to_h3(56, 0, 15)

AttributeError: module 'h3' has no attribute 'geo_to_h3'

**Fix:**

(There are alternative fixes.)

Edit Lib\site-packages\h3\__init__.py from:

from h3 import *  # noqa

to relative import:

from .h3 import *

**Comment by FenderJazz** [comment]
I'm not any kind of Python expert, but as I think someone said elsewhere, I imagine a proper fix would not export * but only the API proper.

**Comment by ajfriend** [comment]
@FenderJazz, it looks like you're using the older bindings 3.4.3, in which case you should raise any issues here: https://github.com/conda-forge/h3-py-feedstock

We'll try to get the conda version updated to the newer bindings hosted here, which are currently at 3.6.1.

In the meantime, you might try installing the newer bindings with `pip install h3`. Since we're now providing pre-built wheels, many installation issues should now be fixed.

**Comment by FenderJazz** [comment]
Thanks.  This may not be the place to express appreciation for all the effort contributors put in but, well, I've said it now!

**Comment by ajfriend** [comment]
@FenderJazz, the conda has been updated. Let us know if you have any issues!

**Comment by FenderJazz** [comment]
Tried it today: much better, thanks!  No dependency on 'h3', no need to tweak anything, new numpy API etc.!
