### ISSUE TITLE
Problem importing h3

### ISSUE THREAD

**Issue by JCHHeilmann** [uber/h3-py#5]
When importing h3 like in the documentation by doing:
`from h3 import h3`
I get the following error:

> OSError: dlopen(/Users/johannesh/anaconda3/envs/on_demand_mobility_nyc_taxi_rides/lib/python3.7/site-packages/h3/out/libh3.1.dylib, 6): image not found

This also happens for a normal pip install --user installation. I looked in the location, and the /h3/out folder does indeed not exist. I'm not sure what this means, or what exactly is going wrong. Seems to be something during installation?

macOS 10.13.6
python 3.7

Thanks

**Comment by dfellis** [comment]
Can you show the logs when you ran `pip install h3`? It should have built that file during install.

**Comment by JCHHeilmann** [comment]
> pip install h3
> Collecting h3
>   Downloading https://files.pythonhosted.org/packages/34/d4/6f308d821bffe97d3b44562f8c90c1f4d858660727d127b935555f3b7877/h3-3.0.0.tar.gz
> Building wheels for collected packages: h3
>   Running setup.py bdist_wheel for h3 ... done
>   Stored in directory: /Users/johannesh/Library/Caches/pip/wheels/82/7d/64/4ae6875a8415e9e364271e4a70872f014a4a9e1fbd67c0ac9c
> Successfully built h3
> Installing collected packages: h3
> Successfully installed h3-3.0.0


The module itself can be found. If I run
```
import h3
print(h3)
```
The result is

> <module 'h3' from '/Users/johannesh/anaconda3/envs/on_demand_mobility_nyc_taxi_rides/lib/python3.7/site-packages/h3/__init__.py'>

**Comment by TengHu** [comment]
Thanks for reporting this, JCHHeilmann. I will look into it asap.

**Comment by isaacbrodsky** [comment]
I believe this is related to a problem where the exit code of the install script isn't checked. Could you post the output of:

```
which cc
which make
which cmake
```

**Comment by JCHHeilmann** [comment]
```
which cc:
    /usr/bin/cc
which make:
    /usr/bin/make
```
`which cmake` doesn't return anything...

**Comment by TengHu** [comment]
Hey @JCHHeilmann,  

Does it work if you install h3 from source ? 

`git clone https://github.com/uber/h3-py.git
cd h3-py
sh .install.sh`

**Comment by JCHHeilmann** [comment]
That doesn't work. I get `.install.sh: line 24: /Users/johannesh/projects/h3-py/h3c/cmake-download/bin/cmake: cannot execute binary file`

Thank you for your help this far.

Full log of install from source:

```
sh .install.sh
+ mkdir -p h3/out
+ rm -rf h3c
+ git clone https://github.com/uber/h3.git h3c
Cloning into 'h3c'...
remote: Counting objects: 1681, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 1681 (delta 20), reused 42 (delta 15), pack-reused 1621
Receiving objects: 100% (1681/1681), 17.19 MiB | 2.40 MiB/s, done.
Resolving deltas: 100% (890/890), done.
+ pushd h3c
~/projects/h3-py/h3c ~/projects/h3-py
+ git pull origin master --tags
From https://github.com/uber/h3
 * branch            master     -> FETCH_HEAD
Already up to date.
+ cmake -DENABLE_FORMAT=OFF -DBUILD_SHARED_LIBS=ON .
.install.sh: line 14: cmake: command not found
+ mkdir cmake-download
+ pushd cmake-download
~/projects/h3-py/h3c/cmake-download ~/projects/h3-py/h3c ~/projects/h3-py
+ curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.4M  100 31.4M    0     0  2471k      0  0:00:13  0:00:13 --:--:-- 5861k
+ bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license
CMake Installer Version: 3.10.0-rc5, Copyright (c) Kitware
This is a self-extracting archive.
The archive will be extracted to: /Users/johannesh/projects/h3-py/h3c/cmake-download

Using target directory: /Users/johannesh/projects/h3-py/h3c/cmake-download
Extracting, please wait...

Unpacking finished successfully
++ pwd
+ export PATH=/Users/johannesh/projects/h3-py/h3c/cmake-download/bin:/Users/johannesh/anaconda3/bin:/Users/johannesh/Library/Python/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
+ PATH=/Users/johannesh/projects/h3-py/h3c/cmake-download/bin:/Users/johannesh/anaconda3/bin:/Users/johannesh/Library/Python/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
+ echo /Users/johannesh/projects/h3-py/h3c/cmake-download/bin:/Users/johannesh/anaconda3/bin:/Users/johannesh/Library/Python/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
/Users/johannesh/projects/h3-py/h3c/cmake-download/bin:/Users/johannesh/anaconda3/bin:/Users/johannesh/Library/Python/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
+ popd
~/projects/h3-py/h3c ~/projects/h3-py
+ cmake -DENABLE_FORMAT=OFF -DBUILD_SHARED_LIBS=ON .
.install.sh: line 24: /Users/johannesh/projects/h3-py/h3c/cmake-download/bin/cmake: cannot execute binary file
```

**Comment by dfellis** [comment]
We need to update the README to call out the `make` and `cmake` dependencies for the package. Can you install `cmake` (through `brew` or however you manager your Mac) and see if that fixes things?

**Comment by JCHHeilmann** [comment]
Yes that was the issue. I installed cmake and then uninstalled h3 and deleted the pip cache. After that the installation worked properly.

Thank you all for your help. I'm looking forward to using h3 for binning geo coordinates instead of geohashs. It seems a lot more optimal 👍.

**Comment by rodmaz** [comment]
I am having exactly the same problem when using `pipenv` to install h3. I do have however the compiler tools in my `$PATH`:

```
- which cc
/usr/bin/cc
- which make
/Applications/Xcode.app/Contents/Developer/usr/bin/make
- which cmake
/usr/local/bin/cmake
```

When I install h3 from my project (pipenv) environment, it does install it successfully but `/out` directory is empty and obviously the needed `libh3.1.dylib` is not available.

```
OSError: dlopen(/Users/rodrigo/.local/share/virtualenvs/myproject--NqKkPOW/lib/python3.7/site-packages/h3/out/libh3.1.dylib, 6): image not found
```

Any ideas?

**Comment by howardmalec** [comment]
@rodmaz - experiencing the same issue

**Comment by someshwardash-rapido** [comment]
^ Same issue

**Comment by karentycoon** [comment]
@rodmaz Your make was not under /usr/bin/... directory. That could be the reason it cannot find make.
Could you try either 
1. have your make installed under /usr/bin directory or
2. add "/Applications/Xcode.app/Contents/Developer/usr/bin" to your PATH variable?

**Comment by rodmaz** [comment]
@karentycoon There are all in my `$PATH`. There is no error or warning complaining about not finding any of those tools. It installs successfully but the `/out` directory is empty.
When I build it from scratch it works perfectly, which is another sign that something is wrong with the `h3` installation from pip.

**Comment by mohit-udaan** [comment]
I was having the same issue. Here are the steps that worked for me.
1: Installed cmake using brew.
2: in the virtual environment, a) pip uninstall h3. b) removed pip cache (/Users/*/Library/Caches/pip)
3: redo: pip install h3

**Comment by rodmaz** [comment]
@mohit-udaan I did that several times. Also `cmake` was installed from `brew` as you suggested.

**Comment by karentycoon** [comment]
@rodmaz are you running in Linux or OSX environment? Could you show the logs when you install h3? If it is still not working, could you try install from source code by 
`git clone https://github.com/uber/h3-py.git 
cd h3-py 
sh .install.sh`

**Comment by rodmaz** [comment]
OK, here is the problem. Trying to install h3 using `pipenv install` clearly does not work. 
`pipenv install h3` returns in package being installed but without C binaries being compiled.

However when we using pip it does work:

`pipenv run pip install h3`

This is probably be a problem when deploying it in production environments.

**Comment by rodmaz** [comment]
See ticket #33

**Comment by BrendanJM** [comment]
For what it's worth, none of these fixes worked for me (while using a fresh `venv` environment). However, I tried using `virtualenv` and was able to install from source without issues.

**Comment by dankoh** [comment]
If someone else is struggling and the steps above do not help I  did this`sudo xcode-select --reset` and it fixed the xcode issue and I could successfully install it afterwards.

(https://stackoverflow.com/questions/35009531/xcrun-error-active-developer-path-applications-xcode-app-contents-developer)
