### ISSUE TITLE
invalid hexagon showing up as valid?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#53]
I think `h = '8a28308280fffff'` is an invalid hexagon address. However, `h3_is_valid(h)` returns `True`. This is coming up because my Cython implementation claims it is **not** valid, and I get segfaults when running algorithms like `k_ring` on this hexagon.

Also, converting to lat/lng and then back to H3 gets a different hexagon, which makes me think the hexagon is actually invalid.

`h3.geo_to_h3(*h3.h3_to_geo(h), res=10) != h`

**Comment by isaacbrodsky** [comment]
`8a28308280fffff` is invalid because the 10th indexing digit is `7` (invalid direction). You can see this with `h3ToComponents` filter application. I'm seeing this returning not valid using `h3-3.4.3`.

```
In [1]: from h3 import h3

In [2]: h3.h3_is_valid('8a28308280fffff')
Out[2]: False

In [3]: h3.h3_is_valid('8928308280fffff')
Out[3]: True
```

**Comment by TengHu** [comment]
my h3.h3_is_valid returns False for '8a28308280fffff'. Also it seems h3_to_geo is not aware of the validity of hexagon and may return a valid one if the input is invalid.

**Comment by ajfriend** [comment]
Got it. I think I was running an older version of H3py. The new Cython branch identifies it correctly as invalid.
