### ISSUE TITLE
The geojson coordinate ordering for h3 inputs doesn't match the spec

### ISSUE THREAD

**Issue by ritviknv** [uber/h3-py#60]
Not really an issue but a bit of an inconvenience: the geojson spec indicates that coordinates should be listed as lng/lat, but python-H3 requires a geojson-like format with the opposite order (lat/lng). Other python gis tools, like Shapely, use lng/lat, as does postgis. 

The geojson object used in the following [example](https://pypi.org/project/h3/) would not be valid by [this spec](https://tools.ietf.org/html/rfc7946): 
```
geoJson = {'type': 'Polygon',
 'coordinates': [[[37.813318999983238, -122.4089866999972145],
 [ 37.7866302000007224, -122.3805436999997056 ],
 [37.7198061999978478, -122.3544736999993603],
 [ 37.7076131999975672, -122.5123436999983966 ],
 [37.7835871999971715, -122.5247187000021967],
 [37.8151571999998453, -122.4798767000009008]]] }
```

**Comment by SteveAlexander** [comment]
I'd like to offer a data point in agreement with this: In my project, I have an `h3_flipped.py`wrapper that provides the H3 API, but with everything (including the geojson coordinates) in lon/lat order. I've found about 80% of Python libraries I use are in lon/lat, 15% in lat/lon, and 5% neither and use keyword arguments to keep things explicit.

To try and avoid confusion, I've standardized on lon/lat everywhere, and wrap any library that works differently.

**Comment by nrabinowitz** [comment]
Note that `polyfill`, `h3_set_to_multi_polygon`, and `h3_to_geo_boundary` all take an extra parameter that offers output (or input, in the case of `polyfill`) in `lng/lat` order. The only function that doesn't is `h3_to_geo`, and this is simple enough to reverse if needed.
