### ISSUE TITLE
Upgrade to newer version and add missing bindings

### ISSUE THREAD

**Issue by ozren1983** [uber/h3-py#68]
Currently h3 is at version 3.6.0, while h3-py is slightly falling behind with version 3.4.3.

Also, compared to API reference, a lot of functions are missing, e.g.: maxFaceCount, maxKringSize, maxH3ToChildrenSize, maxUncompactSize, maxPolyfillSize, h3SetToLinkedGeo, destroyLinkedPolygon

I'm willing to contribute with this if you're accepting pull requests?

**Comment by isaacbrodsky** [comment]
Hi, we've been focusing on getting a Cython-based Python binding ready to replace the existing binding implementation, but while that's still in progress we'd welcome PRs to improve the current one.

I think the functions that are missing should be `h3ToCenterChild`, `getPentagonIndexes` and `h3GetFaces`. Most of the `max...Size` functions are only needed for interfacing with the C library (for allocating buffers of the correct size) and we haven't been exposing them in the bindings so far.

**Comment by ajfriend** [comment]
Closed by https://github.com/uber/h3-py/pull/134, and available in v3.6.3.
