### ISSUE TITLE
Empty `polyfill()` output for large Polygons?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#70]
I was working on the `cython` branch, and created a simple test case for `polyfill()`. However, this example seems to fail in both the `cython` branch and the current `master` branch. Is the issue that the polygon is too large? This seems like an issue with the C library.

Maybe `polyfill()` fails when we hit a pentagon? Should we return an error code in this case?

Here's the code, the output of `polyfill()` is the empty set, which doesn't seem correct.

```python
import h3

box = [[
    [-110.61, 42.68],
    [-109.02, 32.17],
    [ -94.26, 31.57],
    [ -89.38, 42.94],
    [-110.61, 42.68]
]]

json = {
    'type': 'Polygon',
    'coordinates': box,
}

h3.polyfill(json, 3)
```

Here's what the polygon looks like:

<img width="1095" alt="Screen Shot 2019-10-05 at 5 29 54 PM" src="https://user-images.githubusercontent.com/984039/66262478-d7500600-e795-11e9-824a-3e10a68f2b9d.png">

**Comment by ajfriend** [comment]
Dah, dangit. Just a lat/lng vs lng/lat thing...

**Comment by tony-zeidan** [comment]
I'm having a similar problem, I used polygons representing every province of Canada and it worked, but when I included sea areas too, using polyfill for each polygon returned 0 h3_cell id's.

**Comment by tony-zeidan** [comment]
Any idea why the exact same situation with the values:
`[[[-84.94207431820979, -179.0740289306448], [-84.94207431820979, 181.48588919397494], [89.08416132063344, 181.48588919397494], [89.08416132063344, -179.0740289306448], [-84.94207431820979, -179.0740289306448]]]`
would not be working?

**Comment by nrabinowitz** [comment]
At present, if any segment in the polygon is greater than 180 degrees of longitude, we assume the polygon covers the smaller area (in this case, across the antimeridian). So your polygon spans 181.5 to -179 longitude, which I think we'd normalize to -178.5 to -179 longitude, and depending on the resolution there are likely no cells within the 0.5 degrees covered.

The easiest fix at present is to divide the shape into multiple polygons, each less than 180 degrees wide, polyfill each, and union the results.
